- name: Import VPC output variables
  ansible.builtin.include_vars:
    file: vars/vpc-output_vars

- name: Import Bastion output variables
  ansible.builtin.include_vars:
    file: vars/bastion-output_vars

- name: Import Vprofile setup variables
  ansible.builtin.include_vars:
    file: vars/vprostacksetup