---
# =========================================================
# VPROFILE AWS INFRASTRUCTURE WITH ALL THE THREE PLAYBOOKS VPC, BASTION AND DESTROY
# =========================================================

- name: Vprofile VPC
  import_playbook: vpc-setup.yml
  tags:
    - create
    - vpc


- name: Vprofile Bastion
  import_playbook: bastion-instance.yml
  tags:
    - create
    - bastion


- name: Destroy Vprofile Infrastructure
  import_playbook: destroy.yml
  tags:
    - destroy